XGBoost - Add evals argument to fit to support eval on datasets other than training
NVIDIA-Merlin/models pull request #538
Opened 2022-06-28 09:01 UTC by oliverholworthy

Fixes #526 

### Goals :soccer:

A common pattern when using XGBoost is to pass a different dataset (e.g. validation data) to be monitored when training. We would like to support this functionality by allowing users of the XGBoost class to specify these datasets

### Implementation Details :construction:

- Adding new parameter evals to the fit method which accepts a list of tuples similar to the evals expected by the xgboost train function. The difference is that we expcect a Merlin Dataset instead of a DMatrix here.

### Testing Details :mag:

Test added for custom eval. We check the evals result returned by the training.

2022-06-29 10:55 UTC, radekosmulski requested changes
Our implementation dies with a hard to understand error when the eval dataset name is not a single string.

Other than that looks good!

![image](https://user-images.githubusercontent.com/2444926/176420244-0e97025b-a45d-4f0e-8372-2ac6ac839c31.png)

2022-06-29 11:03 UTC, radekosmulski requested changes

2022-06-29 11:11 UTC, oliverholworthy commented on merlin/models/xgb/__init__.py
> +        return self.booster
I was unsure what to return here too. The Merlin Models tensorflow API and Keras return a keras history callback from the fit method which allows you to inspect the metrics that were computed while running.

I suppose the closest equivalent here would be the evals_result dictionary. Or we need to think about what would be consistent across the whole project.

2022-06-30 02:53 UTC, radekosmulski approved these changes

2022-06-30 02:55 UTC, merged